In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
%matplotlib qt

In [3]:
ver_normal = np.load("ver_normals.npy")

In [4]:
ver_normal.shape

(778, 3)

In [5]:
ver = np.load("ver.npy")
ver.shape

(778, 3)

In [6]:
ver[:10]

array([[   8.70069434,  100.86067452, -374.64774672],
       [   0.83661297,  119.85019655, -369.6449892 ],
       [  20.88574597,  114.00937983, -358.24874971],
       [  26.81758832,   95.74418344, -365.03614563],
       [  10.41815953,  158.42255407, -350.74191308],
       [  20.66663038,  180.04409734, -356.88666077],
       [  44.20643477,  160.95678115, -346.29537036],
       [  32.49029907,  145.10911691, -341.30317328],
       [  44.83086315,   91.45039323, -362.48084748],
       [  37.55857233,  108.33737544, -351.56557651]])

In [17]:
c = np.ones((100, 3))
up_mask = ver_normal[:100, 2] > 0
# np.where(up_mask, [1, 1, 1], [0, 0, 0])
c[up_mask, :] = [0, 0, 0]
np.pi / 4

0.7853981633974483

In [22]:
vec = ver_normal[0, :]
vec = np.array([0, 1, 1])
angle = np.arcsin(np.abs(vec[2]) / np.linalg.norm(vec))
vec, angle

def calc_angle(vec):
    return np.arcsin(np.abs(vec[2]) / np.linalg.norm(vec))
np.apply_along_axis(calc_angle, 1, ver_normal[:num_arrow, :]) < (np.pi / 6)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False])

In [23]:
# soa = np.array([[0, 0, 0, 1, -2, 0], [0, 0, 0, 1, 1, 0],
#                 [0, 0, 0, 2, 1, 0], [0, 0, 0, 0.5, 0.7, 0]])

def calc_angle(vec):
    return np.arcsin(np.abs(vec[2]) / np.linalg.norm(vec))

num_arrow = 100

soa = np.concatenate([np.zeros((778, 3)), ver_normal], axis=1)[:50]
soa = np.concatenate([ver, ver_normal * 50], axis=1)[:num_arrow]

# soa = np.concatenate([np.zeros((778, 3)), ver_normal - ver], axis=1)[:50]

X, Y, Z, U, V, W = zip(*soa)


# # Color by azimuthal angle
# c = np.arctan2(V, U)
# # Flatten and normalize
# c = (c.ravel() - c.min()) / c.ptp()
# # Repeat for each body line and two head lines
# c = np.concatenate((c, np.repeat(c, 2)))
# # Colormap
# c = plt.cm.hsv(c)

# c = np.ones((100, 3)) / 2

c = np.ones((num_arrow, 3))
up_mask = ver_normal[:num_arrow, 2] > 0
c[up_mask, :] = [0.6, 0.5, 0.4]
side_mask = np.apply_along_axis(calc_angle, 1, ver_normal[:num_arrow, :]) < (np.pi / 6)
c[side_mask, :] = [0.9, 0.6, 0.8]


up_mask = ver_normal[:, 2] > 0






fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.quiver(X, Y, Z, U, V, W, colors=c)
size = 200
ax.set_xlim([-100, 100])
ax.set_ylim([-50, 200])
ax.set_zlim([-500, -300])
plt.show()

In [41]:
up_mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,

In [46]:
up_mask.nonzero()[0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  24,  25,  26,  27,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  53,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  79,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 122, 123, 124, 125, 126, 128, 129, 130, 131,
       132, 137, 138, 139, 140, 141, 142, 146, 147, 148, 149, 150, 151,
       152, 154, 155, 156, 157, 159, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 188, 189, 194, 195, 196, 197, 198, 199, 223, 228,
       237, 238, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 251,
       252, 254, 255, 257, 262, 264, 265, 266, 267, 268, 271, 273, 275,
       278, 280, 281, 284, 285, 288, 297, 298, 300, 301, 309, 317, 320,
       321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 33

In [22]:
soa = np.concatenate([np.zeros((778, 3)), ver_normal - ver], axis=1)[:50]

soa = np.concatenate([np.zeros((778, 3)), ver_normal], axis=1)[:100]

X, Y, Z, U, V, W = zip(*soa)


# # Color by azimuthal angle
# c = np.arctan2(V, U)
# # Flatten and normalize
# c = (c.ravel() - c.min()) / c.ptp()
# # Repeat for each body line and two head lines
# c = np.concatenate((c, np.repeat(c, 2)))
# # Colormap
# c = plt.cm.hsv(c)

c = np.ones((100, 3)) / 2




fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.quiver(X, Y, Z, U, V, W, colors=c)
size = 200
ax.set_xlim([-1, 1])
ax.set_ylim([-1, 1])
ax.set_zlim([-1, 1])
plt.show()

In [52]:
up_idx = np.load("up_idx.npy")

In [54]:
up_idx.shape

(439,)